### ISSUE TITLE
"Ereignis" text on the image

### ISSUE THREAD

**Issue by TheSoulrester** [dj0001/DWD-Warnmodul-2#4]
Hi, 

the text "ereignis" is on the image. will this be possible to be fixed?
![image](https://user-images.githubusercontent.com/7083599/120831489-dde0e300-c55f-11eb-8582-bab25abd47bf.png)

**Comment by dj0001** [comment]
replace `<td>Ereignis&nbsp;:`
with `<td style='width:50px'>` or `<td style='visibility:hidden'>Ereignis&nbsp;:`
in https://github.com/dj0001/DWD-Warnmodul-2/blob/master/src/leaflet-betterwms_dj.js#L98

**Comment by TheSoulrester** [comment]
Ok, thank you
